bot.yml - GitHub Actions workflow to run the bot on a schedule.
name: AI News Tweeter

on:
schedule:
# Runs at 12:00 PM UTC every day.
- cron: "0 12 * * *"

Allows manual triggering of the workflow from the GitHub UI.
workflow_dispatch:

jobs:
run-bot:
runs-on: ubuntu-latest
steps:
- name: Checkout repository
uses: actions/checkout@v3

  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: 18

  - name: Install dependencies
    run: npm install

  - name: Run bot script
    run: node index.js
    # Inject secrets as environment variables during the run
    env:
      HUGGING_FACE_API_KEY: ${{ secrets.HUGGING_FACE_API_KEY }}
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
